version: '3'
services:
  magento:
    build:
        context: ./apache
        dockerfile: Dockerfile.php71
    ports:
      - 8071:80
    volumes:
      - ./magento:/var/www/html
    networks:
      - webnet
