version: '3'
services:
  magento:
    image: php:7.2.13-apache
    ports:
      - 8080-8089:80
    networks:
      - webnet

  db:
    image: percona:5.7.23
    environment:
      MYSQL_ROOT_PASSWORD: magento
    networks:
      - webnet
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8060-8069:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8020-8029:8025
    networks:
      - webnet

networks:
  webnet:
